---

- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    rocket_url: rocket.pharriso.co.uk
  vars_prompt:
    - name: pat_user
      prompt: "PAT user"
      private: no
    - name: pat_token
      prompt: "PAT token"
      private: no
    - name: student_password
      prompt: "Student password"
      private: no
  tasks:
  - name: add users
    uri:
      url: https://{{ rocket_url }}/api/v1/users.create
      method: POST
      body: '{"name": "student{{ item }}", "email": "student{{ item }}@localhost.com", "password": "{{ student_password }}", "username": "student{{ item }}"}'
      headers: 
        X-Auth-Token: "{{ pat_token }}"
        X-User-Id: "{{ pat_user }}"
        Content-type: "application/json"
      body_format: json
    loop: "{{ range(1, 100 + 1)| list }}"
